# Generated by Django 2.1 on 2019-05-29 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190529_0824'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productdetail',
            name='category',
        ),
        migrations.RemoveField(
            model_name='productdetail',
            name='trim',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='ProductDetail',
        ),
    ]
