# Generated by Django 2.2.1 on 2019-05-27 07:25

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190527_0637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trim',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
    ]
